exclude: |
  (?x)(
      .vscode/(.)* |
      utils/generate-test-checks.py |
      LICENSE
  )
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-json
        exclude: .vscode/settings.rec.json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: mixed-line-ending
      - id: debug-statements
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.7
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        language: system
        # entry: clang-format -i --style=file
        entry: |
          bash -c '
          if ! command -v clang-format >/dev/null; then exit 0; fi
          clang-format -i --style=file "$@"
          ' --
        types_or: [c, c++]
      - id: clang-include-cleaner
        name: clang-include-cleaner
        language: system
        # entry: clang-include-cleaner -edit -disable-insert -p build
        entry: |
          bash -c '
          if [ ! -d build ] || ! command -v clang-include-cleaner >/dev/null; then exit 0; fi
          clang-include-cleaner -edit -disable-insert -p build "$@"
          ' --
        types_or: [c, c++]
