[workspace]
authors = ["Allen Guo <guosonglin001@gmail.com>"]
channels = ["conda-forge"]
name = "triton-xyz"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.2,<3.15"
uv = ">=0.9.26,<0.10"
ruff = ">=0.14.13,<0.15"
ty = ">=0.0.13,<0.0.14"

pytest = ">=9.0.2,<10"
pre-commit = ">=4.5.1,<5"

[activation.env]
# needs llvm-triton
PATH = "${PIXI_PROJECT_ROOT}/build/bin:${PIXI_PROJECT_ROOT}/llvm-triton/llvm-project/build/bin:${PATH}"
