[workspace]
authors = ["Allen Guo <guosonglin001@gmail.com>"]
channels = ["conda-forge"]
name = "triton-xyz"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.13.*"
uv = ">=0.9.26,<0.10"
ruff = ">=0.14.13,<0.15"
ty = ">=0.0.13,<0.0.14"
debugpy = ">=1.8.20,<2"

pre-commit = ">=4.5.1,<5"
pytest = ">=9.0.2,<10"
lit = ">=21.1.8,<22"

pytorch = ">=2.9.1,<3"
pybind11 = ">=3.0.1,<4"
pybind11-global = ">=3.0.1,<4"

[activation.env]
# needs llvm-triton
PATH = "${PIXI_PROJECT_ROOT}/build/bin:${PIXI_PROJECT_ROOT}/llvm-triton/llvm-project/build/bin:${PATH}"
